-- Rollback van migratie 0019 (stap 5, cross-reference integriteit). Verwijdert alleen triggers en functies;
-- er is geen data of schema gewijzigd, dus er is niets terug te zetten. Geen app-rollback nodig.
begin;
drop trigger if exists xref_open_tabs on public.open_tabs;
drop trigger if exists xref_cost_centers on public.cost_centers;
drop trigger if exists xref_receipts on public.receipts;
drop trigger if exists xref_invoices on public.invoices;
drop trigger if exists xref_invoice_lines on public.invoice_lines;
drop trigger if exists xref_approvals on public.approvals;
drop trigger if exists xref_company_scoped on public.configurations;
drop trigger if exists xref_company_scoped on public.workflow_rules;
drop trigger if exists xref_documents on public.documents;
drop trigger if exists xref_user_ref on public.receipts;
drop trigger if exists xref_user_ref on public.daily_closings;
drop trigger if exists xref_user_ref on public.notifications;
drop trigger if exists xref_user_ref on public.activity_log;
drop trigger if exists xref_user_ref on public.domain_events;
drop trigger if exists xref_user_ref on public.audit_log;
drop trigger if exists xref_keys_immutable on public.companies;
drop trigger if exists xref_keys_immutable on public.departments;
drop trigger if exists xref_keys_immutable on public.cost_centers;
drop trigger if exists xref_keys_immutable on public.projects;
drop trigger if exists xref_keys_immutable on public.contacts;
drop trigger if exists xref_keys_immutable on public.open_tabs;
drop trigger if exists xref_keys_immutable on public.receipts;
drop trigger if exists xref_keys_immutable on public.invoices;
drop function if exists public.xref_open_tabs();
drop function if exists public.xref_cost_centers();
drop function if exists public.xref_receipts();
drop function if exists public.xref_invoices();
drop function if exists public.xref_invoice_lines();
drop function if exists public.xref_approvals();
drop function if exists public.xref_company_scoped();
drop function if exists public.xref_documents();
drop function if exists public.xref_user_ref();
drop function if exists public.xref_keys_immutable();
drop function if exists public.xref_company_in_restaurant(uuid, uuid);
commit;
